# Generated by Django 4.0.4 on 2022-06-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_so_net', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Posts',
        ),
        migrations.RenameField(
            model_name='users_likes',
            old_name='post',
            new_name='posts',
        ),
    ]
